# Generated by Django 5.1.1 on 2024-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_option', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2')], max_length=100)),
                ('devices', models.JSONField()),
                ('time_interval', models.CharField(max_length=50)),
                ('prediction_model', models.CharField(max_length=100)),
                ('V_rms', models.FloatField()),
                ('I_rms', models.FloatField()),
                ('P', models.FloatField()),
                ('S', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('custom_model_file', models.FileField(blank=True, null=True, upload_to='custom_models/')),
            ],
        ),
    ]
